import React, {FC} from 'react';
import {Col, Row, Table} from "react-bootstrap";

const CompanyBackground: FC = () => {
  return (
    <Row className='mx-0'>
      <Col xs={12}>
        <ul className='points'>
          <li>
            Sanasto is a distribution agency for cosmetics and pharmaceutical products. It was started 5 years ago. It's
            an organization run by a local entrepreneur Mr. W.J Sunil who is the sole owner of this business.
          </li>
          <br/>
          <li>
            They focus on distributing products imported by Alaris Lanka (Pvt) Ltd which imports very popular cosmetics
            pharmaceutical and Nutraceutical product brands to Sri Lanka.
          </li>
          <br/>
          <li>
            From Point Pedro to Dondra, there are around 25 Distributors strategically positioned throughout key cities.
            They maintain a network to reach consumers in every corner of their area using the resources we supply and
            the facilities they have. Sales staff optimize the facilities to ensure that our items are available to
            selected consumers within 24 hours of making an order, in order to meet the company's expectations in each
            region.
          </li>
          <br/>
          <li>
            Sanasto is one of their distribution agencies which operates mainly in the areas of Balangoda, Ratnapura,
            Eheliyagoda, Sooriyawewa.
          </li>
          <br/>
          <li>
            Their main revenue is generated by the commission they receive from distributing products to the pharmacies
            in respective areas they have agreed on the contract with Aloris Lanka to distribute their product.
          </li>
        </ul>
        <p className='section-title'>Industry Leaders</p>
        <ol className='points'>
          <li>
            Hemas Pharmaceuticals
            <ul>
              <li>
                One of the leading importer and distributor of pharmaceutical, surgical, and diagnostic products in the
                Sri Lankan market with over six decades of experience in the healthcare industry.
              </li>
              <li>
                Extending to all parts of the country, Hemas distributes to all of the country’s pharmacies, private
                hospitals, supermarkets, and other private and government institutions with a synergized IT system
                tailor made for inventory management and distribution.
              </li>
            </ul>
          </li>
          <br/>
          <li>
            Wettasinghe Pharmaceutical Distributors
            <ul>
              <li>
                Beginning its operations in 1998, Wettasinghe Pharmaceutical Distributors are one of the largest
                distributors of generic pharmaceuticals in Colombo and suburbs.
              </li>
              <li>
                The company is the Authorized distributor for State Pharmaceuticals Corporation (SPC), State
                Pharmaceuticals and Manufacturing Corporation (SPMC), Alaris Lanka, Morisons PLC, and also stocks
                products of other pharmaceutical companies where necessary.
              </li>
            </ul>
          </li>
        </ol>
        <br/>
        <p className='section-title'>Sanasto vs. Industry Leaders</p>
        <Table striped bordered hover responsive>
          <thead>
          <tr>
            <th>Comparison Factor</th>
            <th>Hemas Pharmaceuticals</th>
            <th>Wettasinghe Pharmaceutical Distributors</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Experience</td>
            <td>60 years +</td>
            <td>22 years +</td>
          </tr>
          <tr>
            <td>Scale</td>
            <td>650+ Employees</td>
            <td>-</td>
          </tr>
          <tr>
            <td>Strategies</td>
            <td>
              <ul className='points'>
                <li>
                  Utilize the latest technologies
                </li>
                <li>
                  SS-functional sharing of information by utilizing the world-renowned Enterprise Resource Planning
                  (ERP) solution SAP
                </li>
                <li>Customized tracking systems</li>
              </ul>
            </td>
            <td>
              <ul className='points'>
                <li>
                  The company is the Authorized distributor for State Pharmaceuticals Corporation (SPC), State
                  Pharmaceuticals and Manufacturing Corporation (SPMC), Alaris Lanka and it has a strong presence
                </li>
                <li>
                  They have implemented their own set of policies and standards that have helped them to build a
                  trustworthy and loyal client base
                </li>
              </ul>
            </td>
          </tr>
          </tbody>
        </Table>
      </Col>
    </Row>
  );
}

export default CompanyBackground;
